- name: prepend hostbased authentication setting to ssh_config
  blockinfile:
    path: "{{ ssh_hostbased_auth_ssh_config_file }}"
    insertbefore: BOF
    block: |
      HostBasedAuthentication yes
      EnableSSHKeysign yes
      NoHostAuthenticationForLocalhost yes
