- name: initialize allowed host lists
  set_fact:
    ssh_hostbased_auth_allowed_ips: []
    ssh_hostbased_auth_allowed_hostnames: []
    ssh_hostbased_auth_allowed_fqdns: []

- name: convert specified allowed hosts to IP address
  set_fact:
    ssh_hostbased_auth_allowed_ips: "{{ ssh_hostbased_auth_allowed_ips + [lookup('dig',item)|replace('NXDOMAIN',item)|replace('localhost','127.0.0.1')] }}"
  loop: "{{ ssh_hostbased_auth_allowed_hosts }}"

- name: remove duplicates
  set_fact:
    ssh_hostbased_auth_allowed_ips: "{{ ssh_hostbased_auth_allowed_ips|flatten|unique}}"

- name: convert IP address to fqdn
  set_fact:
    ssh_hostbased_auth_allowed_fqdns: "{{ ssh_hostbased_auth_allowed_fqdns + [lookup('dig',item,'qtype=PTR').rstrip('.')|replace('127.0.0.1','localhost')] }}"
  loop: "{{ ssh_hostbased_auth_allowed_ips }}"

- name: convert fqdn to hostname
  set_fact:
    ssh_hostbased_auth_allowed_hostnames: "{{ ssh_hostbased_auth_allowed_hostnames + [ item.split('.')[0] ] }}"
  loop: "{{ ssh_hostbased_auth_allowed_fqdns }}"

- name: make sshd setting
  set_fact:
    ssh_hostbased_auth_sshd_config: "HostbasedAuthentication yes"

- name: restrict authentication method only to hostbased
  set_fact:
    ssh_hostbased_auth_sshd_config: "{{ ssh_hostbased_auth_sshd_config }} \nAuthenticationMethods hostbased"
  when: ssh_hostbased_auth_only

- name: allow root login
  set_fact:
    ssh_hostbased_auth_sshd_config: "{{ ssh_hostbased_auth_sshd_config }} \nPermitRootLogin prohibit-password\nIgnoreRhosts no"
  when: ssh_hostbased_auth_permit_root_login

- name: prepend hostbased authentication setting to sshd_config
  blockinfile:
    path: "{{ ssh_hostbased_auth_sshd_config_file }}"
    insertbefore: BOF
    block: "{{ ssh_hostbased_auth_sshd_config }}"
  notify: restart_sshd


- name: change ssh-keysign's permission
  file:
    path: "{{ ssh_hostbased_auth_ssh_keysign}}"
    owner: root
    group: root
    mode:  04755

- block:
  - name: gather host key and store it to facts
    include_tasks: keyscan.yml
    with_items: "{{ ssh_hostbased_auth_allowed_ips + ssh_hostbased_auth_allowed_hostnames }}"
    loop_control:
      loop_var: target

  - name: write host keys to known_hosts file
    copy:
      dest: "{{ ssh_hostbased_auth_known_hosts_file }}"
      content: "{{ host_key }}"

  - name: write hostnames to shots.equiv file
    copy:
      dest: "{{ ssh_hostbased_auth_shosts_equiv_file }}"
      content: "{{ ( ssh_hostbased_auth_allowed_ips + ssh_hostbased_auth_allowed_hostnames + ssh_hostbased_auth_allowed_fqdns ) | join('\n') }}"

  - name: write hostnames to root/shosts
    copy:
      dest: "/root/.shosts"
      content: "{{ ( ssh_hostbased_auth_allowed_ips + ssh_hostbased_auth_allowed_hostnames + ssh_hostbased_auth_allowed_fqdns ) | join('\n') }}"
    when: ssh_hostbased_auth_permit_root_login
  when: ssh_hostbased_auth_allowed_ips |length >0